print("Required packages are loading...")

library('sessioninfo')
library('XML')
library('methods')
library('httr')
library('xts')
library('lubridate')
library('tidymodels')
library('ggthemes')
library('zoo')
library('PerformanceAnalytics')
library('forecast')
library('modeltime')
library('timetk')
library('skimr')
library('quantmod')
library("tidyverse")
library('rmarkdown')
library('flexdashboard')

print("Packages are loaded successfully")
