print("Required packages are loading...")

load('sessioninfo')
load('XML')
load('methods')
load('httr')
load('xts')
load('lubridate')
load('tidymodels')
load('ggthemes')
load('zoo')
load('PerformanceAnalytics')
load('forecast')
load('modeltime')
load('timetk')
load('skimr')
load('quantmod')

print("Packages are loaded successfully")
