print("Installation started")

install.packages('sessioninfo')
install.packages('XML')
install.packages('methods')
install.packages('httr')
install.packages('xts')
install.packages('lubridate')
install.packages('tidymodels')
install.packages('ggthemes')
install.packages('zoo')
install.packages('PerformanceAnalytics')
install.packages('forecast')
install.packages('modeltime')
install.packages('timetk')
install.packages('skimr')
install.packages('quantmod')

print("Packages are installed successfully")
